trigger:
  - feature/azure-devops-builds

variables:
  CONFIGURATION: 'Debug'
  NRF_BLE_DRIVER_VERSION: '4.1.0'
  NRF_BLE_CONNECTIVITY_VERSION: $(NRF_BLE_DRIVER_VERSION)
  NRF_BLE_DRIVER_ARTIFACT_PREFIX: nrf-ble-driver-$(NRF_BLE_DRIVER_VERSION)
  NRF_BLE_DRIVER_INSTALL_PREFIX: artifacts/$(NRF_BLE_DRIVER_ARTIFACT_PREFIX)
  GITHUB_CONNECTION: 'waylandCI'
  GITHUB_REPO: 'NordicSemiconductor/pc-ble-driver'
  GITHUB_TAG: v$(NRF_BLE_DRIVER_VERSION)
  VCPKG_REPOSITORY: 'https://github.com/Microsoft/vcpkg.git'
  VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg'

jobs:
- job: Build
  strategy:
    matrix:
      win32:
        imageName: 'vs2017-win2016'
        architecture: 'x86'
        generator_platform: 'Win32'
        vcpkg_triplet: 'x86-windows'
        vcvars_path: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/vc/Auxiliary/build/vcvarsall.bat"
  pool:
    vmImage: $(imageName)
  steps:
  - script: |
      cmake --version
      pip3 install -r %BUILD_SOURCESDIRECTORY%\.azure-pipelines\requirements.txt
      python %BUILD_SOURCESDIRECTORY%\.azure-pipelines\nordic_setup.py --prefix=$(Agent.BuildDirectory)/toolchain --tcversion nRF5_SDK_v16.0.0 --env > $(Agent.BuildDirectory)\tcenv.bat
      choco install ninja make
    condition: contains(variables['imageName'], 'win')
    displayName: '[Windows] Install build dependencies'
  - script: |
      @echo off
      echo "VCPKG_ROOT is %VCPKG_ROOT%"
      git clone $(VCPKG_REPOSITORY) %VCPKG_ROOT%
      cd /d %VCPKG_ROOT%
      bootstrap-vcpkg.bat
      cd /d $(Build.SourcesDirectory)
    condition: contains(variables['imageName'], 'win')
    displayName: '[Windows] Install vcpkg'
  - script: |
      %VCPKG_ROOT%\vcpkg install asio:$(vcpkg_triplet) catch2:$(vcpkg_triplet) spdlog:$(vcpkg_triplet)
    condition: contains(variables['imageName'], 'win')
    displayName: '[Windows] Install pc-ble-driver dependencies'
  - script: |
      @echo off
      call "$(vcvars_path)" $(architecture)
      del "C:\ProgramData\chocolatey\bin\c++.exe"
      del "C:\ProgramData\chocolatey\bin\g++.exe"
      del "C:\ProgramData\chocolatey\bin\gcc.exe"
      del "C:\Strawberry\c\bin\c++.exe"
      del "C:\Strawberry\c\bin\g++.exe"
      del "C:\Strawberry\c\bin\gcc.exe"
      call $(Agent.BuildDirectory)/tcenv.bat
      set PATH=%PATH%;%BUILD_SOURCESDIRECTORY%\.azure-pipelines\tools\win32
      echo Setting install directory to $(Build.ArtifactStagingDirectory)
      echo Creating project files
      cmake -H. -B_build -GNinja -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory) -DBUILD_SHARED_LIBS=ON -DCOMPILE_CONNECTIVITY=1 -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DNRF_BLE_DRIVER_VERSION=$(NRF_BLE_DRIVER_VERSION)

      if %ERRORLEVEL% neq 0 (
        echo Error generating project file
        exit -1
      )

      echo Executing target compile_connectivity
      cmake --build _build --config $(CONFIGURATION) --target compile_connectivity

      if %ERRORLEVEL% neq 0 (
        echo Error compiling connectivity
        exit -1
      )

      echo Executing target install
      cmake --build _build --config $(CONFIGURATION) --target install

      if %ERRORLEVEL% neq 0 (
        echo Error installing
        exit -1
      )
    condition: contains(variables['imageName'], 'win')
    displayName: '[Windows] Run cmake and build project'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: pc-ble-driver-$(Agent.OS)-$(architecture)

# Test jobs below this point
- job: test_win86
  displayName: 'Test Win32'
  dependsOn: 'Build'
  pool:
    name: test-pool
    demands: Agent.OS -equals Windows_NT
  variables:
    TEST_REPORT_DIR: $(System.DefaultWorkingDirectory)\tests
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'current'
      artifact: 'pc-ble-driver-$(Agent.OS)-x86'
  - script: |
      mkdir %TEST_REPORT_DIR%

      set ITERATIONS=10
      cmake -DBOARD=pca10028 -DSD_TYPE=s130 -DSD_VERSION=2.0.1 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10031 -DSD_TYPE=s130 -DSD_VERSION=2.0.1 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10040 -DSD_TYPE=s132 -DSD_VERSION=3.1.0 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10040 -DSD_TYPE=s132 -DSD_VERSION=5.1.0 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10040 -DSD_TYPE=s132 -DSD_VERSION=6.1.1 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10056 -DSD_TYPE=s132 -DSD_VERSION=3.1.0 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10056 -DSD_TYPE=s132 -DSD_VERSION=5.1.0 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake
      cmake -DBOARD=pca10056 -DSD_TYPE=s140 -DSD_VERSION=6.1.1 -DITERATIONS=%ITERATIONS% -DCONNECTIVITY_VERSION=$(NRF_BLE_CONNECTIVITY_VERSION) -DINSTALL_DIRECTORY=$(Pipeline.Workspace) -DTEST_OUTPUT_DIRECTORY=$(TEST_REPORT_DIR) -P .azure-pipelines/run_test.cmake

    continueOnError: true
    failOnStderr: false
    displayName: 'Run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-result.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Linux tests'
    condition: succeededOrFailed()
